/* tslint:disable:max-line-length */
export const positiveData = [
  'Escort Nicoleta Langley to field in Whitewhyte where they can meet with their long lost pot,Gamble',
  'Escort Peggy Simmons to peninsula in Southtown where they can meet with their long lost turnips,Quite likely',
  'Help Mahlah Rowntree to sell an unordinary sheep on the local market,Hmmm....',
  'Message:Help Clovis Summerfield to write their biographical novel about their difficulties with a deranged pan,Walk in the park',
  'Escort Brahma Guðmundsdóttir to pasture in Southhill where they can meet with their long lost turnips,Hmmm....',
  'Help defending plains in Westkeep from the intruders,Quite likely',
  'Help defending village in Razorkeep from the intruders,Quite likely',
  'Help defending plains in Westkeep from the intruders,Quite likely',
  'Help defending steppe in Bloodloft from the intruders,Risky',
  'Escort Marc Jardine to peninsula in Lightsheen where they can meet with their long lost sheep,Quite likely',
  'Help Miĥaelo Brownlow to sell an unordinary beer mug on the local market,Walk in the park',
  'Steal dog delivery to Sindre Bennett and share some of the profits with the people,Quite likely',
  'Escort Domenica Þórhalldóttir to peninsula in Masonburg where they can meet with their long lost cat,Risky',
  'Create an advertisement campaign for Honza Bloodworth to promote their house based business,Walk in the park',
  'Escort Mihajlo Sinclair to meadow in Fallham where they can meet with their long lost horse,Rather detrimental',
];

export const negativeData = [
  'Escort Pauli Webster to grassland in Millergarden where they can meet with their long lost water,Walk in the park',
  'Create an advertisement campaign for Gershon Hambleton to promote their squirrel based business,Quite likely',
  'Create an advertisement campaign for Viivi Steinauer to promote their squirrel based business,Hmmm...',
  'Help defending savannah in Sharpfair from the intruders,Walk in the park',
  'Help Jaleh Hackett to write their biographical novel about their difficulties with a deranged water,Gamble',
  'Help Tamela Lesassier to write their biographical novel about their difficulties with a deranged beer mug,Playing with fire',
  'Escort Latoya Butcher to grassland in Greygarden where they can meet with their long lost chariot, Hmmm....',
  'Help Wilbert Morison to write their biographical novel about their difficulties with a deranged turnips, Playing with fire',
  'Create an advertisement campaign for Mwanajuma Forrest to promote their cat based business,Rather detrimental',
  'Help Saliha Kimberley to write their biographical novel about their difficulties with a deranged clothes,Risky',
  'Create an advertisement campaign for Jonas Henryson to promote their pot based business,Walk in the park',
  'Help Clémentine Sargent to reach an agreement with Artemon Strange on the matters of disputed wagon,Gamble',
  'Create an advertisement campaign for Tero Pearson to promote their potatoes based business,Gamble',
  'Help Lanny Shelton to sell an unordinary sheep on the local market,Playing with fire',
  'Investigate Larunda Scrivener and find out their relation to the magic squirrel.,Playing with fire',
  'Steal super awesome diamond water from Jermaine Farnham,Sure thing',
  'Steal beer mug delivery to Jayadeva Jónsson and share some of the profits with the people.,Walk in the park',
  'Help Gregor Nathanson to sell an unordinary weed on the local market,Walk in the park',
  'Help Lleucu Everett to clean their pan,Walk in the park',
  'Help Freddie Chambers to transport a magic pot to thrift shoppe in Lightgannon,Quite likely',
  'Help Srinivas Trueman to sell an unordinary sheep on the local market,Quite likely',
  'Create an advertisement campaign for Lyosha Wardrobe to promote their weed based business,Quite likely',
];
